
library(tidyverse)
library(AIMutils)
library(DBI)
library(keyring)

INFOACCESScon <- AIMutils::open.INFOACCESS.connection()


advisor_notes <- DBI::dbGetQuery(INFOACCESScon, 
                                 "SELECT 
  UW.STDNT_ADVISOR_NOTES.*,
  UW.RETENTION_STUDENT.GENDER,
  UW.RETENTION_STUDENT.TUITION_RESIDENCY_AT_ENTRANCE,
  UW.RETENTION_STUDENT.FALL_COHORT_YEAR,
  UW.RETENTION_STUDENT.FIRST_SEMESTER_ENROLLED,
  UW.STDNT_ETHNIC_REPORTING.ETHNIC_REPORTING_DESCR,
  UW.STDNT_ETHNIC_REPORTING.ETHNIC_REPORTING_CODE,
  UW.STDNT_ETHNIC_REPORTING.MINORITY,
  UW.STDNT_ETHNIC_REPORTING.TARGETED_MINORITY,
  UW.STDNT_ETHNIC_REPORTING.HISPANIC,
  UW.STDNT_ETHNIC_REPORTING.AFRICAN_AMERICAN,
  UW.STDNT_ETHNIC_REPORTING.AMERICAN_INDIAN,
  UW.STDNT_ETHNIC_REPORTING.ASIAN,
  UW.STDNT_ETHNIC_REPORTING.NATIVE_HAWAIIAN,
  UW.STDNT_ETHNIC_REPORTING.WHITE
FROM UW.STDNT_ADVISOR_NOTES
INNER JOIN UW.STDNT_ETHNIC_REPORTING
ON UW.STDNT_ETHNIC_REPORTING.ID = UW.STDNT_ADVISOR_NOTES.ID
INNER JOIN UW.RETENTION_STUDENT
ON UW.RETENTION_STUDENT.ID = UW.STDNT_ADVISOR_NOTES.ID
WHERE UW.STDNT_ADVISOR_NOTES.ADVISING_UNIT_ID = '461'
AND UW.STDNT_ADVISOR_NOTES.NOTE_CREATED_BY != 'EDNA'")


STU_LENGTH <- length(unique(advisor_notes$ID))

students <- advisor_notes |>
              select(ID) |>
            unique()

students$Random_ID  <-  as.character(round(runif(STU_LENGTH, 999999999, 9999999999), 0))

sum(duplicated(students$Random_ID))


advisor_notes.data <- advisor_notes |> 
                 inner_join(students, by = "ID") |>
                select(-ID, -CAMPUS_ID) |>
            relocate(Random_ID, .before = ADVISOR_ID)

openxlsx::write.xlsx(advisor_notes.data, file = "Random_ADS_Advisor_Notes.xlsx")
